import { loadSettings, section } from "@blogagent/config";

/**
 * sink-pinterest's configuration in one place: settings.yaml values, the OAuth
 * secrets, and the constants that used to sit inline (scopes, the .env path).
 * index.js reads from here — never from process.env or loadSettings directly.
 *
 * Naming convention: UPPERCASE fields are static literals baked in here (never read
 * from settings.yaml); camelCase fields come from settings.yaml or the environment.
 *
 * `buildConfig` is pure (settings + env in, config out) so it is unit-testable with
 * fakes and never throws on a plain read; `config` is the live instance the running
 * service uses. There is no assertSecrets: Pinterest runs in DRY RUN without
 * credentials, so nothing is strictly required at boot — the service reports its
 * authorization state itself.
 *
 * `directToken` and `initialRefreshToken` are seed values. The running service keeps
 * the refresh token (and the fetched access token) in mutable state; config is the
 * boot snapshot, not the live token.
 */
export function buildConfig(settings, env) {
  const cfg = section(settings, "sink-pinterest");
  // Required, no default — a misconfigured port must fail loudly.
  const port = cfg.num("port");
  return {
    port,
    apiUrl: cfg.str("api_url", "https://api.pinterest.com"),
    boardId: cfg.str("board_id"),
    // Must match the URI registered in the Pinterest app EXACTLY (port and path included).
    redirectUri: cfg.str("redirect_uri", `http://localhost:${port}/oauth/callback`),
    SCOPES: ["pins:write", "boards:read"],
    ENV_PATH: ".env",
    appId: env.PINTEREST_APP_ID ?? "",
    appSecret: env.PINTEREST_APP_SECRET ?? "",
    // A token generated by hand in the Pinterest app dashboard. It bypasses OAuth
    // entirely (no app secret) and cannot be refreshed.
    directToken: env.PINTEREST_ACCESS_TOKEN ?? "",
    // Seeds the in-memory refresh token (written by a previous OAuth run).
    initialRefreshToken: env.PINTEREST_REFRESH_TOKEN ?? "",
  };
}

export const config = buildConfig(loadSettings(), process.env);
